Wnz phi3
mikecovlee/mLoRA pull request #90
Opened 2024-07-28 03:45 UTC by Pherenice1125

Support LoRA eager attention, flash attention2 and sliding window for Phi3-mini-128k-instruct @mikecovlee

2024-07-28 06:39 UTC, mikecovlee requested changes

2024-07-28 06:39 UTC, mikecovlee commented on mlora/common/mix_lora.py
plz remove the comments. this file should not be modified.

2024-07-28 06:39 UTC, mikecovlee commented on model_archi.txt
this file should not included in pr. plz remove it.

2024-07-28 06:39 UTC, mikecovlee commented on 1.json
remove this test file.

2024-07-28 06:39 UTC, mikecovlee commented on 2.json
remove this test file.

2024-07-28 09:35 UTC, Pherenice1125 commented on mlora/common/mix_lora.py
Already removed.

2024-07-28 09:35 UTC, Pherenice1125 commented on model_archi.txt
Already removed.

2024-07-28 09:35 UTC, Pherenice1125 commented on 1.json
Already removed.

2024-07-28 09:35 UTC, Pherenice1125 commented on 2.json
Already removed.

2024-07-29 07:13 UTC, mikecovlee commented
ARC-C + LoRA = 84.2%

2024-07-29 07:55 UTC, mikecovlee approved these changes

2024-07-29 08:09 UTC, merged